import { Patient, Doctor, Nurse, Staff, Department, Appointment } from '@/types';

export let patients: Patient[] = [
  { id: 1001, name: "Emma Thompson", age: 34, gender: "Female", contact: "555-0123", bloodGroup: "O+", address: "12 Park Avenue" },
  { id: 1002, name: "Michael Chen", age: 45, gender: "Male", contact: "555-0456", bloodGroup: "A-", address: "45 Ocean Drive" },
  { id: 1003, name: "Aisha Khan", age: 29, gender: "Female", contact: "555-0789", bloodGroup: "B+", address: "78 Maple Street" },
  { id: 1004, name: "David Okoro", age: 52, gender: "Male", contact: "555-1122", bloodGroup: "O-", address: "23 River Road" },
  { id: 1005, name: "Fatima Al-Sayed", age: 31, gender: "Female", contact: "555-3344", bloodGroup: "AB+", address: "91 Sunset Blvd" },
  { id: 1006, name: "James Rodriguez", age: 67, gender: "Male", contact: "555-5566", bloodGroup: "A+", address: "67 Pine Lane" },
  { id: 1007, name: "Priya Sharma", age: 24, gender: "Female", contact: "555-7788", bloodGroup: "B-", address: "34 Elm Street" },
  { id: 1008, name: "John Mensah", age: 41, gender: "Male", contact: "555-9900", bloodGroup: "O+", address: "12 Liberty Ave" },
  { id: 1009, name: "Sophia Laurent", age: 38, gender: "Female", contact: "555-2233", bloodGroup: "A-", address: "55 Harbor View" },
  { id: 1010, name: "Ahmed Hassan", age: 55, gender: "Male", contact: "555-4455", bloodGroup: "B+", address: "89 Mountain Road" },
  { id: 1011, name: "Grace Okafor", age: 27, gender: "Female", contact: "555-6677", bloodGroup: "O-", address: "22 Garden Close" },
  { id: 1012, name: "Carlos Mendoza", age: 49, gender: "Male", contact: "555-8899", bloodGroup: "AB+", address: "17 Central Park" },
  { id: 1013, name: "Linda Wang", age: 33, gender: "Female", contact: "555-1010", bloodGroup: "A+", address: "64 Lakeview" },
  { id: 1014, name: "Kwame Boateng", age: 62, gender: "Male", contact: "555-1212", bloodGroup: "B-", address: "33 Ridge Way" },
  { id: 1015, name: "Maria Silva", age: 26, gender: "Female", contact: "555-3434", bloodGroup: "O+", address: "88 Beachfront" },
  { id: 1016, name: "Robert Kim", age: 44, gender: "Male", contact: "555-5656", bloodGroup: "A-", address: "11 High Street" },
  { id: 1017, name: "Ananya Patel", age: 30, gender: "Female", contact: "555-7878", bloodGroup: "B+", address: "77 Queen’s Road" },
  { id: 1018, name: "Samuel Adebayo", age: 39, gender: "Male", contact: "555-9090", bloodGroup: "O-", address: "50 Freedom Lane" },
  { id: 1019, name: "Elena Petrova", age: 35, gender: "Female", contact: "555-2323", bloodGroup: "AB+", address: "29 Sunrise Ave" },
  { id: 1020, name: "Daniel Moreau", age: 48, gender: "Male", contact: "555-4545", bloodGroup: "A+", address: "15 Valley View" },
];

export let doctors: Doctor[] = [
  { id: 1, name: "Dr. Sarah Williams", specialization: "Cardiology", department: "Cardiology", availability: "Available", phone: "555-1001", experience: 12 },
  { id: 2, name: "Dr. Raj Patel", specialization: "Neurology", department: "Neurology", availability: "Busy", phone: "555-1002", experience: 8 },
  { id: 3, name: "Dr. Fatima Okoro", specialization: "Pediatrics", department: "Pediatrics", availability: "Available", phone: "555-1003", experience: 15 },
  { id: 4, name: "Dr. Michael Chen", specialization: "Orthopedics", department: "Orthopedics", availability: "Available", phone: "555-1004", experience: 10 },
  { id: 5, name: "Dr. Aisha Khan", specialization: "Gynecology", department: "Obstetrics & Gynecology", availability: "On Leave", phone: "555-1005", experience: 9 },
  { id: 6, name: "Dr. John Mensah", specialization: "General Surgery", department: "Surgery", availability: "Available", phone: "555-1006", experience: 14 },
  { id: 7, name: "Dr. Priya Sharma", specialization: "Internal Medicine", department: "Internal Medicine", availability: "Busy", phone: "555-1007", experience: 7 },
  { id: 8, name: "Dr. Carlos Rodriguez", specialization: "Oncology", department: "Oncology", availability: "Available", phone: "555-1008", experience: 11 },
  { id: 9, name: "Dr. Grace Okafor", specialization: "Radiology", department: "Radiology", availability: "Available", phone: "555-1009", experience: 6 },
  { id: 10, name: "Dr. Ahmed Hassan", specialization: "Emergency Medicine", department: "Emergency", availability: "Busy", phone: "555-1010", experience: 13 },
];

export let nurses: Nurse[] = [
  { id: 2001, name: "Nurse Abigail Mensah", department: "Pediatrics", shift: "Morning", phone: "555-2001", experience: 5, status: "Active" },
  { id: 2002, name: "Nurse Fatima Bello", department: "Cardiology", shift: "Evening", phone: "555-2002", experience: 8, status: "Active" },
  { id: 2003, name: "Nurse James Okoro", department: "Surgery", shift: "Night", phone: "555-2003", experience: 4, status: "On Leave" },
  { id: 2004, name: "Nurse Priya Nair", department: "Obstetrics & Gynecology", shift: "Morning", phone: "555-2004", experience: 7, status: "Active" },
  { id: 2005, name: "Nurse Samuel Adeyemi", department: "Emergency", shift: "Night", phone: "555-2005", experience: 6, status: "Active" },
  { id: 2006, name: "Nurse Aisha Yusuf", department: "Internal Medicine", shift: "Evening", phone: "555-2006", experience: 3, status: "Active" },
  { id: 2007, name: "Nurse Michael Okafor", department: "Orthopedics", shift: "Morning", phone: "555-2007", experience: 9, status: "Active" },
  { id: 2008, name: "Nurse Grace Chen", department: "Neurology", shift: "Night", phone: "555-2008", experience: 5, status: "On Leave" },
  { id: 2009, name: "Nurse David Kim", department: "Oncology", shift: "Evening", phone: "555-2009", experience: 4, status: "Active" },
  { id: 2010, name: "Nurse Sophia Laurent", department: "Pediatrics", shift: "Morning", phone: "555-2010", experience: 6, status: "Active" },
  { id: 2011, name: "Nurse Kwame Boateng", department: "Emergency", shift: "Night", phone: "555-2011", experience: 7, status: "Active" },
  { id: 2012, name: "Nurse Maria Silva", department: "Cardiology", shift: "Evening", phone: "555-2012", experience: 5, status: "Active" },
  { id: 2013, name: "Nurse Emmanuel Adebayo", department: "Surgery", shift: "Morning", phone: "555-2013", experience: 6, status: "Active" },
  { id: 2014, name: "Nurse Linda Wong", department: "Internal Medicine", shift: "Evening", phone: "555-2014", experience: 4, status: "Active" },
  { id: 2015, name: "Nurse Carlos Rivera", department: "Pediatrics", shift: "Night", phone: "555-2015", experience: 8, status: "Active" },
  { id: 2016, name: "Nurse Fatima Diallo", department: "Obstetrics & Gynecology", shift: "Morning", phone: "555-2016", experience: 5, status: "Active" },
  { id: 2017, name: "Nurse Robert Kim", department: "Orthopedics", shift: "Evening", phone: "555-2017", experience: 3, status: "Active" },
  { id: 2018, name: "Nurse Ananya Sharma", department: "Neurology", shift: "Night", phone: "555-2018", experience: 7, status: "Active" },
  { id: 2019, name: "Nurse John Mensah", department: "Emergency", shift: "Morning", phone: "555-2019", experience: 6, status: "On Leave" },
  { id: 2020, name: "Nurse Priya Patel", department: "Cardiology", shift: "Evening", phone: "555-2020", experience: 5, status: "Active" },
  { id: 2021, name: "Nurse Samuel Okafor", department: "Surgery", shift: "Night", phone: "555-2021", experience: 4, status: "Active" },
  { id: 2022, name: "Nurse Grace Okoro", department: "Pediatrics", shift: "Morning", phone: "555-2022", experience: 9, status: "Active" },
  { id: 2023, name: "Nurse Ahmed Yusuf", department: "Internal Medicine", shift: "Evening", phone: "555-2023", experience: 5, status: "Active" },
  { id: 2024, name: "Nurse Elena Petrova", department: "Oncology", shift: "Night", phone: "555-2024", experience: 6, status: "Active" },
  { id: 2025, name: "Nurse Daniel Moreau", department: "Radiology", shift: "Morning", phone: "555-2025", experience: 4, status: "Active" },
];

export let staff: Staff[] = [
  { id: 3001, name: "Mr. Robert Lee", role: "Pharmacist", department: "Pharmacy", phone: "555-3001", status: "Active" },
  { id: 3002, name: "Ms. Linda Wang", role: "Lab Technician", department: "Laboratory", phone: "555-3002", status: "Active" },
  { id: 3003, name: "Mr. Carlos Rivera", role: "Radiology Technician", department: "Radiology", phone: "555-3003", status: "On Leave" },
  { id: 3004, name: "Ms. Ananya Gupta", role: "HR Manager", department: "Administration", phone: "555-3004", status: "Active" },
  { id: 3005, name: "Mr. Emmanuel Ojo", role: "Accountant", department: "Finance", phone: "555-3005", status: "Active" },
  { id: 3006, name: "Ms. Elena Petrova", role: "Medical Records Officer", department: "Administration", phone: "555-3006", status: "Active" },
  { id: 3007, name: "Mr. Daniel Moreau", role: "IT Support", department: "Technical", phone: "555-3007", status: "Active" },
  { id: 3008, name: "Ms. Fatima Diallo", role: "Physiotherapist", department: "Rehabilitation", phone: "555-3008", status: "Active" },
  { id: 3009, name: "Mr. Kwesi Annan", role: "Security Supervisor", department: "Security", phone: "555-3009", status: "Active" },
  { id: 3010, name: "Ms. Sophia Rodriguez", role: "Dietitian", department: "Nutrition", phone: "555-3010", status: "Active" },
];

export let departments: Department[] = [
  { id: 1, name: "Cardiology", headDoctor: "Dr. Sarah Williams", doctorCount: 8 },
  { id: 2, name: "Neurology", headDoctor: "Dr. Raj Patel", doctorCount: 6 },
  { id: 3, name: "Pediatrics", headDoctor: "Dr. Fatima Okoro", doctorCount: 10 },
  { id: 4, name: "Orthopedics", headDoctor: "Dr. Michael Chen", doctorCount: 7 },
  { id: 5, name: "Obstetrics & Gynecology", headDoctor: "Dr. Aisha Khan", doctorCount: 9 },
  { id: 6, name: "General Surgery", headDoctor: "Dr. John Mensah", doctorCount: 8 },
  { id: 7, name: "Internal Medicine", headDoctor: "Dr. Priya Sharma", doctorCount: 12 },
  { id: 8, name: "Oncology", headDoctor: "Dr. Carlos Rodriguez", doctorCount: 5 },
  { id: 9, name: "Radiology", headDoctor: "Dr. Grace Okafor", doctorCount: 6 },
  { id: 10, name: "Emergency Medicine", headDoctor: "Dr. Ahmed Hassan", doctorCount: 11 },
  { id: 11, name: "ENT", headDoctor: "Dr. Samuel Adebayo", doctorCount: 4 },
  { id: 12, name: "Ophthalmology", headDoctor: "Dr. Linda Wang", doctorCount: 5 },
  { id: 13, name: "Dermatology", headDoctor: "Dr. Maria Silva", doctorCount: 4 },
  { id: 14, name: "Gastroenterology", headDoctor: "Dr. Robert Kim", doctorCount: 6 },
  { id: 15, name: "Psychiatry", headDoctor: "Dr. Ananya Patel", doctorCount: 5 },
];

export let appointments: Appointment[] = [
  { id: 501, patientName: "Emma Thompson", doctorName: "Dr. Sarah Williams", date: "2026-05-10", time: "09:30", status: "Scheduled" },
  { id: 502, patientName: "Michael Chen", doctorName: "Dr. Raj Patel", date: "2026-05-10", time: "11:00", status: "Scheduled" },
  { id: 503, patientName: "Aisha Khan", doctorName: "Dr. Fatima Okoro", date: "2026-05-10", time: "14:15", status: "Completed" },
  { id: 504, patientName: "David Okoro", doctorName: "Dr. Michael Chen", date: "2026-05-11", time: "08:45", status: "Scheduled" },
  { id: 505, patientName: "Fatima Al-Sayed", doctorName: "Dr. Priya Sharma", date: "2026-05-11", time: "10:30", status: "Scheduled" },
  { id: 506, patientName: "James Rodriguez", doctorName: "Dr. John Mensah", date: "2026-05-11", time: "13:00", status: "Cancelled" },
  { id: 507, patientName: "Priya Sharma", doctorName: "Dr. Grace Okafor", date: "2026-05-12", time: "09:15", status: "Scheduled" },
  { id: 508, patientName: "John Mensah", doctorName: "Dr. Ahmed Hassan", date: "2026-05-12", time: "15:45", status: "Completed" },
  { id: 509, patientName: "Sophia Laurent", doctorName: "Dr. Sarah Williams", date: "2026-05-13", time: "11:30", status: "Scheduled" },
  { id: 510, patientName: "Ahmed Hassan", doctorName: "Dr. Carlos Rodriguez", date: "2026-05-13", time: "14:00", status: "Scheduled" },
];