import { Nurse, Staff, Department, Appointment } from '@/types';

// export let patients: Patient[] = [
//   { 
//     id: 1001, 
//     name: "Emma Thompson", 
//     age: 34, 
//     gender: "Female", 
//     contact: "555-0123", 
//     bloodGroup: "O+", 
//     address: "12 Park Avenue", 
//     status: 'Outpatient',
//     doctor: "Dr. Sarah Williams",
//     ward: "Cardiology",
//     condition: "High Blood Pressure",
//     admitDate: "2026-05-15"
//   },
//   { 
//     id: 1002, 
//     name: "Michael Chen", 
//     age: 45, 
//     gender: "Male", 
//     contact: "555-0456", 
//     bloodGroup: "A-", 
//     address: "45 Ocean Drive", 
//     status: 'Admitted',
//     doctor: "Dr. Raj Patel",
//     ward: "Neurology",
//     condition: "Severe Headache",
//     admitDate: "2026-05-20"
//   },
//   { 
//     id: 1003, 
//     name: "Aisha Khan", 
//     age: 29, 
//     gender: "Female", 
//     contact: "555-0789", 
//     bloodGroup: "B+", 
//     address: "78 Maple Street", 
//     status: 'Discharged',
//     doctor: "Dr. Fatima Okoro",
//     ward: "Pediatrics",
//     condition: "After Childbirth",
//     admitDate: "2026-04-28"
//   },
//   { 
//     id: 1004, 
//     name: "David Okoro", 
//     age: 52, 
//     gender: "Male", 
//     contact: "555-1122", 
//     bloodGroup: "O-", 
//     address: "23 River Road", 
//     status: 'Outpatient',
//     doctor: "Dr. Michael Chen",
//     ward: "Orthopedics",
//     condition: "Knee Pain",
//     admitDate: "2026-05-18"
//   },
//   { 
//     id: 1005, 
//     name: "Fatima Al-Sayed", 
//     age: 31, 
//     gender: "Female", 
//     contact: "555-3344", 
//     bloodGroup: "AB+", 
//     address: "91 Sunset Blvd", 
//     status: 'Admitted',
//     doctor: "Dr. Aisha Khan",
//     ward: "Gynecology",
//     condition: "Pregnancy Complications",
//     admitDate: "2026-05-22"
//   },
//   { 
//     id: 1006, 
//     name: "James Chukwu", 
//     age: 67, 
//     gender: "Male", 
//     contact: "555-5566", 
//     bloodGroup: "A+", 
//     address: "67 Pine Lane", 
//     status: 'Critical',
//     doctor: "Dr. Sarah Williams",
//     ward: "ICU",
//     condition: "Heart Attack",
//     admitDate: "2026-05-25"
//   },
//   { 
//     id: 1007, 
//     name: "Priya Sharma", 
//     age: 24, 
//     gender: "Female", 
//     contact: "555-7788", 
//     bloodGroup: "B-", 
//     address: "34 Elm Street", 
//     status: 'Admitted',
//     doctor: "Dr. Priya Sharma",
//     ward: "Internal Medicine",
//     condition: "Malaria",
//     admitDate: "2026-05-19"
//   },
//   { 
//     id: 1008, 
//     name: "John Mensah", 
//     age: 41, 
//     gender: "Male", 
//     contact: "555-9900", 
//     bloodGroup: "O+", 
//     address: "12 Liberty Ave", 
//     status: 'Critical',
//     doctor: "Dr. John Mensah",
//     ward: "Surgical",
//     condition: "Appendicitis",
//     admitDate: "2026-05-24"
//   },
//   { 
//     id: 1009, 
//     name: "Sophia Laurent", 
//     age: 38, 
//     gender: "Female", 
//     contact: "555-2233", 
//     bloodGroup: "A-", 
//     address: "55 Harbor View", 
//     status: 'Admitted',
//     doctor: "Dr. Aisha Khan",
//     ward: "Gynecology",
//     condition: "Fibroids",
//     admitDate: "2026-05-21"
//   },
//   { 
//     id: 1010, 
//     name: "Ahmed Hassan", 
//     age: 55, 
//     gender: "Male", 
//     contact: "555-4455", 
//     bloodGroup: "B+", 
//     address: "89 Mountain Road", 
//     status: 'Outpatient',
//     doctor: "Dr. Ahmed Hassan",
//     ward: "Emergency",
//     condition: "Diabetes",
//     admitDate: "2026-05-23"
//   },
//   { 
//     id: 1011, 
//     name: "Grace Okafor", 
//     age: 27, 
//     gender: "Female", 
//     contact: "555-6677", 
//     bloodGroup: "O-", 
//     address: "22 Garden Close", 
//     status: 'Admitted',
//     doctor: "Dr. Grace Okafor",
//     ward: "Radiology",
//     condition: "Chest Infection",
//     admitDate: "2026-05-26"
//   },
//   { 
//     id: 1012, 
//     name: "Carlos Mendoza", 
//     age: 49, 
//     gender: "Male", 
//     contact: "555-8899", 
//     bloodGroup: "AB+", 
//     address: "17 Central Park", 
//     status: 'Discharged',
//     doctor: "Dr. Carlos Rodriguez",
//     ward: "Oncology",
//     condition: "Cancer Treatment",
//     admitDate: "2026-04-15"
//   },
//   { 
//     id: 1013, 
//     name: "Linda Wang", 
//     age: 33, 
//     gender: "Female", 
//     contact: "555-1010", 
//     bloodGroup: "A+", 
//     address: "64 Lakeview", 
//     status: 'Critical',
//     doctor: "Dr. Sarah Williams",
//     ward: "ICU",
//     condition: "Heart Problem",
//     admitDate: "2026-05-27"
//   },
//   { 
//     id: 1014, 
//     name: "Kwame Boateng", 
//     age: 62, 
//     gender: "Male", 
//     contact: "555-1212", 
//     bloodGroup: "B-", 
//     address: "33 Ridge Way", 
//     status: 'Admitted',
//     doctor: "Dr. Michael Chen",
//     ward: "Orthopedics",
//     condition: "Broken Leg",
//     admitDate: "2026-05-20"
//   },
//   { 
//     id: 1015, 
//     name: "Maria Silva", 
//     age: 26, 
//     gender: "Female", 
//     contact: "555-3434", 
//     bloodGroup: "O+", 
//     address: "88 Beachfront", 
//     status: 'Admitted',
//     doctor: "Dr. Aisha Khan",
//     ward: "Gynecology",
//     condition: "Pregnancy Issue",
//     admitDate: "2026-05-22"
//   },
//   { 
//     id: 1016, 
//     name: "Robert Kim", 
//     age: 44, 
//     gender: "Male", 
//     contact: "555-5656", 
//     bloodGroup: "A-", 
//     address: "11 High Street", 
//     status: 'Admitted',
//     doctor: "Dr. Raj Patel",
//     ward: "Neurology",
//     condition: "Stroke",
//     admitDate: "2026-05-19"
//   },
//   { 
//     id: 1017, 
//     name: "Ananya Patel", 
//     age: 30, 
//     gender: "Female", 
//     contact: "555-7878", 
//     bloodGroup: "B+", 
//     address: "77 Queen’s Road", 
//     status: 'Critical',
//     doctor: "Dr. Priya Sharma",
//     ward: "Internal Medicine",
//     condition: "Severe Infection",
//     admitDate: "2026-05-28"
//   },
//   { 
//     id: 1018, 
//     name: "Samuel Adebayo", 
//     age: 39, 
//     gender: "Male", 
//     contact: "555-9090", 
//     bloodGroup: "O-", 
//     address: "50 Freedom Lane", 
//     status: 'Discharged',
//     doctor: "Dr. John Mensah",
//     ward: "Surgical",
//     condition: "Hernia Surgery",
//     admitDate: "2026-05-10"
//   },
//   { 
//     id: 1019, 
//     name: "Elena Petrova", 
//     age: 35, 
//     gender: "Female", 
//     contact: "555-2323", 
//     bloodGroup: "AB+", 
//     address: "29 Sunrise Ave",
//     status: 'Outpatient',
//     doctor: "Dr. Grace Okafor",
//     ward: "Radiology",
//     condition: "Breast Lump",
//     admitDate: "2026-05-24"
//   },
//   { 
//     id: 1020, 
//     name: "Daniel Moreau", 
//     age: 48, 
//     gender: "Male", 
//     contact: "555-4545", 
//     bloodGroup: "A+", 
//     address: "15 Valley View", 
//     status: 'Admitted',
//     doctor: "Dr. Carlos Rodriguez",
//     ward: "Oncology",
//     condition: "Colon Cancer",
//     admitDate: "2026-05-21"
//   },
// ];


export let nurses: Nurse[] = [
  { id: 2001, name: "Nurse Abigail Mensah", department: "Pediatrics", shift: "Morning", phone: "555-2001", experience: 5, status: "On Duty" },
  { id: 2002, name: "Nurse Fatima Bello", department: "Cardiology", shift: "Evening", phone: "555-2002", experience: 8, status: "On Duty" },
  { id: 2003, name: "Nurse James Okoro", department: "Surgery", shift: "Night", phone: "555-2003", experience: 4, status: "On Leave" },
  { id: 2004, name: "Nurse Priya Nair", department: "Obstetrics & Gynecology", shift: "Morning", phone: "555-2004", experience: 7, status: "On Duty" },
  { id: 2005, name: "Nurse Samuel Adeyemi", department: "Emergency", shift: "Night", phone: "555-2005", experience: 6, status: "Off Duty" },
  { id: 2006, name: "Nurse Aisha Yusuf", department: "Internal Medicine", shift: "Evening", phone: "555-2006", experience: 3, status: "On Duty" },
  { id: 2007, name: "Nurse Michael Okafor", department: "Orthopedics", shift: "Morning", phone: "555-2007", experience: 9, status: "On Duty" },
  { id: 2008, name: "Nurse Grace Chen", department: "Neurology", shift: "Night", phone: "555-2008", experience: 5, status: "On Leave" },
  { id: 2009, name: "Nurse David Kim", department: "Oncology", shift: "Evening", phone: "555-2009", experience: 4, status: "Off Duty" },
  { id: 2010, name: "Nurse Sophia Laurent", department: "Pediatrics", shift: "Morning", phone: "555-2010", experience: 6, status: "Off Duty" },
  { id: 2011, name: "Nurse Kwame Boateng", department: "Emergency", shift: "Night", phone: "555-2011", experience: 7, status: "On Duty" },
  { id: 2012, name: "Nurse Maria Silva", department: "Cardiology", shift: "Evening", phone: "555-2012", experience: 5, status: "On Duty" },
  { id: 2013, name: "Nurse Emmanuel Adebayo", department: "Surgery", shift: "Morning", phone: "555-2013", experience: 6, status: "On Duty" },
  { id: 2014, name: "Nurse Linda Wong", department: "Internal Medicine", shift: "Evening", phone: "555-2014", experience: 4, status: "Off Duty" },
  { id: 2015, name: "Nurse Carlos Rivera", department: "Pediatrics", shift: "Night", phone: "555-2015", experience: 8, status: "On Duty" },
  { id: 2016, name: "Nurse Fatima Diallo", department: "Obstetrics & Gynecology", shift: "Morning", phone: "555-2016", experience: 5, status: "On Duty" },
  { id: 2017, name: "Nurse Robert Kim", department: "Orthopedics", shift: "Evening", phone: "555-2017", experience: 3, status: "Off Duty" },
  { id: 2018, name: "Nurse Ananya Sharma", department: "Neurology", shift: "Night", phone: "555-2018", experience: 7, status: "On Duty" },
  { id: 2019, name: "Nurse John Mensah", department: "Emergency", shift: "Morning", phone: "555-2019", experience: 6, status: "On Leave" },
  { id: 2020, name: "Nurse Priya Patel", department: "Cardiology", shift: "Evening", phone: "555-2020", experience: 5, status: "On Duty" },
  { id: 2021, name: "Nurse Samuel Okafor", department: "Surgery", shift: "Night", phone: "555-2021", experience: 4, status: "On Duty" },
  { id: 2022, name: "Nurse Grace Okoro", department: "Pediatrics", shift: "Morning", phone: "555-2022", experience: 9, status: "Off Duty" },
  { id: 2023, name: "Nurse Ahmed Yusuf", department: "Internal Medicine", shift: "Evening", phone: "555-2023", experience: 5, status: "On Duty" },
  { id: 2024, name: "Nurse Elena Petrova", department: "Oncology", shift: "Night", phone: "555-2024", experience: 6, status: "On Duty" },
  { id: 2025, name: "Nurse Daniel Moreau", department: "Radiology", shift: "Morning", phone: "555-2025", experience: 4, status: "On Duty" },
];

export let staff: Staff[] = [
  { id: 3001, name: "Mr. Robert Lee", role: "Pharmacist", department: "Pharmacy", phone: "555-3001", status: "Active" },
  { id: 3002, name: "Ms. Linda Wang", role: "Lab Technician", department: "Laboratory", phone: "555-3002", status: "Active" },
  { id: 3003, name: "Mr. Carlos Rivera", role: "Radiology Technician", department: "Radiology", phone: "555-3003", status: "On Leave" },
  { id: 3004, name: "Ms. Ananya Gupta", role: "HR Manager", department: "Administration", phone: "555-3004", status: "Active" },
  { id: 3005, name: "Mr. Emmanuel Ojo", role: "Accountant", department: "Finance", phone: "555-3005", status: "Active" },
  { id: 3006, name: "Ms. Elena Petrova", role: "Medical Records Officer", department: "Administration", phone: "555-3006", status: "Active" },
  { id: 3007, name: "Mr. Daniel Moreau", role: "IT Support", department: "Technical", phone: "555-3007", status: "Active" },
  { id: 3008, name: "Ms. Fatima Diallo", role: "Physiotherapist", department: "Rehabilitation", phone: "555-3008", status: "Active" },
  { id: 3009, name: "Mr. Kwesi Annan", role: "Security Supervisor", department: "Security", phone: "555-3009", status: "Active" },
  { id: 3010, name: "Ms. Sophia Rodriguez", role: "Dietitian", department: "Nutrition", phone: "555-3010", status: "Active" },
];

export let departments: Department[] = [
  { id: 1, name: "Cardiology", headDoctor: "Dr. Sarah Williams", doctorCount: 8 },
  { id: 2, name: "Neurology", headDoctor: "Dr. Raj Patel", doctorCount: 6 },
  { id: 3, name: "Pediatrics", headDoctor: "Dr. Fatima Okoro", doctorCount: 10 },
  { id: 4, name: "Orthopedics", headDoctor: "Dr. Michael Chen", doctorCount: 7},
  { id: 5, name: "Obstetrics & Gynecology", headDoctor: "Dr. Aisha Khan", doctorCount: 9 },
  { id: 6, name: "General Surgery", headDoctor: "Dr. John Mensah", doctorCount: 8},
  { id: 8, name: "Oncology", headDoctor: "Dr. Carlos Rodriguez", doctorCount: 5},
  { id: 9, name: "Radiology", headDoctor: "Dr. Grace Okafor", doctorCount: 6 },
  { id: 10, name: "Emergency Medicine", headDoctor: "Dr. Ahmed Hassan", doctorCount: 11},
  { id: 12, name: "Ophthalmology", headDoctor: "Dr. Linda Wang", doctorCount: 5 },
  { id: 13, name: "Dermatology", headDoctor: "Dr. Maria Silva", doctorCount: 4},
  { id: 14, name: "Gastroenterology", headDoctor: "Dr. Robert Kim", doctorCount: 6 },
  { id: 15, name: "Psychiatry", headDoctor: "Dr. Ananya Patel", doctorCount: 5 },
];

export let appointments: Appointment[] = [
  { id: 501, patientName: "Emma Thompson", doctorName: "Dr. Sarah Williams", date: "2026-05-10", time: "09:30", status: "Cancelled", type: "Check-up" },
  { id: 502, patientName: "Michael Chen", doctorName: "Dr. Raj Patel", date: "2026-05-10", time: "11:00", status: "Scheduled", type: "Consultation" },
  { id: 503, patientName: "Aisha Khan", doctorName: "Dr. Fatima Okoro", date: "2026-05-10", time: "14:15", status: "Completed", type: "Treatment" },
  { id: 504, patientName: "David Okoro", doctorName: "Dr. Michael Chen", date: "2026-05-11", time: "08:45", status: "Scheduled", type: "Follow-up" },
  { id: 505, patientName: "Fatima Al-Sayed", doctorName: "Dr. Priya Sharma", date: "2026-05-11", time: "10:30", status: "Scheduled", type: "Check-up" },
  { id: 506, patientName: "James Chukwu", doctorName: "Dr. John Mensah", date: "2026-05-11", time: "13:00", status: "Cancelled", type: "Consultation" },
];

export const patientTrendData = [
  { month: "Dec", admitted: 180, discharged: 165, outpatient: 320 },
  { month: "Jan", admitted: 210, discharged: 195, outpatient: 380 },
  { month: "Feb", admitted: 195, discharged: 200, outpatient: 355 },
  { month: "Mar", admitted: 230, discharged: 210, outpatient: 410 },
  { month: "Apr", admitted: 248, discharged: 235, outpatient: 440 },
  { month: "May", admitted: 265, discharged: 250, outpatient: 472 },
];

export const departmentData = [
  { name: "Cardiology", patients: 45, color: "#1e40af" },
  { name: "Emergency Med.", patients: 88, color: "#db2777" },
  { name: "ICU", patients: 22, color: "#10b981" },
  { name: "Orthopedics", patients: 36, color: "#1e40af" },
  { name: "Neurology", patients: 28, color: "#db2777" },
  { name: "Surgery", patients: 31, color: "#10b981" },
   { name: "Gynecology", patients: 12, color:"#1e40af" },
   { name: "Pediatrics", patients: 22, color:"#db2777" },
   { name: "Ophthalmology", patients: 5, color:"#1e40af" },
   { name: "Gastroenterology", patients: 50, color: "#db2777" },
   { name: "Psychiatry", patients: 15, color:"#10b981" },
   { name: "Dermatology", patients: 19, color:"#1e40af" },
   { name: "Obstetrics", patients: 9, color:"#db2777" },
   { name: "Oncology", patients: 11, color:"#10b981" },
   { name: "Radiology", patients: 60, color:"#1e40af" },
];

export const revenueData = [
  { month: "Dec", revenue: 4200000, expenses: 3100000 },
  { month: "Jan", revenue: 4800000, expenses: 3400000 },
  { month: "Feb", revenue: 4500000, expenses: 3200000 },
  { month: "Mar", revenue: 5200000, expenses: 3700000 },
  { month: "Apr", revenue: 5600000, expenses: 3900000 },
  { month: "May", revenue: 6100000, expenses: 4100000 },
];

export const staffStats = {
  doctors: { total: 10, onDuty: 6 },
  nurses: { total: 25, onDuty: 14 },
  other: { total: 15, onDuty: 10 },
};

